### ISSUE TITLE
History overwritten

### ISSUE THREAD

**Issue by villanuevawill** [plasma-group/plasma-client#7]
Problem:
https://github.com/plasma-group/plasma-client/pull/4/files#diff-2cce40143051e25f811b56c79d619bf5

It appears that the recent commit on bringing the DB in overwrote the changes in adding the operator to the client and `Plasma` client options correctly.

The original PR was merged by @kfichter on behalf of @cryptobias

**Comment by villanuevawill** [comment]
Actually https://github.com/plasma-group/plasma-client/commit/a57265b3aee782748114306ae4ebdfd9473289aa overwrote the previous changes.

**Comment by kfichter** [comment]
I made some big changes today, there are a few outstanding bugs I need to fix as a result. Sorry about that :-/ what's the particular issue you're having?

**Comment by villanuevawill** [comment]
@kfichter closing this - old version on js-lib. Cheers and good work :).
